name: ibis-datasette-examples
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - atpublic
  - ffmpeg
  - httpx
  - ipywidgets
  - numpy
  - pandas
  - parsy
  - pydantic
  - pydub
  - rich
  - sqlalchemy
  - toolz
  - pip:
      - git+https://github.com/ibis-project/ibis.git
