name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.rst"
  release:
    types: [published]

jobs:
  lint:
    name: Lint and flake code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Test Dependencies
        run: |
          pip install pytest datasette

      - name: Build
        run: |
          pip install -e .

      - name: Run black & flake8
        uses: pre-commit/action@v2.0.0

      - name: Run tests
        run: py.test -v tests

  build_release:
    name: Build Source Distribution
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install build deps
        run: pip install wheel

      - name: Build source distribution
        run: python setup.py sdist

      - name: Build wheel
        run: python setup.py bdist_wheel --universal

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/

  upload_pypi:
    needs: [build_release]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
